### ISSUE TITLE
Lyfevest asks for 'Organization and Teams'

### ISSUE THREAD

**Issue by RickJWagner** [Lyfevest/lyfevest#1]
GitHub authorization is asking for public repositories (as described in the Lyfevest Contributor Beta signup page), GitHub email address (also described on the signup page) and Organization and Teams (not listed on the signup page.)

GitHub help for 'Organization and Teams' offers help:
"This application will be able to read your organization, team membership, and private project boards. "

Access to this information may be too sensitive for some Organizations/Teams.   Can it be made optional (perhaps by Organization/Team)?

**Comment by qodfathr** [comment]
It's more or less a result of how GitHub OAuth works, which does not permit very fine grained access. In general, however, the org does maintain control, and, in most cases, Lyfevest either cannot see anything in the org or only public artifacts in the org,

For example, I am a member of several organizations. When I register, roughly 1/3 are granted access without asking, 1/3 require me to make a request (which is sent to the org owner for approval), and 1/3 require me to grant access (because I am an owner of the org). So, if I do nothing and take the defaults, Lyfevest only gains access to the orgs which had already pre-approved open access.

Also, note that Lyfevest is only requesting Read-Only access for Orgs:

![image](https://user-images.githubusercontent.com/16322190/63091451-61b18180-bf2c-11e9-8808-44de8e638964.png)

Lyfevest has zero interest beyond publicly available information on GitHub. We'll continue to work with GitHub to improve OAuth permissions controls.

**Comment by qodfathr** [comment]
Thanks again, @RickJWagner, for voicing your concerns. We've made a change to the required OAuth scopes -- in particular, we no longer require `org:read`, which honestly may have been a left-over scope from early testing. We hope this alleviates some of the concerns.

Currently registered users may want to go to GitHub and revoke access to the Lyfevest.io OAuth app:

- Sign out of Lyfvfest.io (using the drop-down menu)
- https://github.com/settings/applications
- Select Authorized OAuth Apps tab
![image](https://user-images.githubusercontent.com/16322190/63175414-f80ba300-c011-11e9-8ea5-abd74e3ab47c.png)
- Click on the `...` next to Lyfevest.io and select Revoke
![image](https://user-images.githubusercontent.com/16322190/63175626-62244800-c012-11e9-9b59-2e533615696d.png)
- Sign back into Lyfevest.io to get new permissions
- - From the home page, click Sign In in upper-right corner
- - Click the GitHub sign in button.
- - You do not need to reenter your beta code or do any of the previous registration steps, assuming you had already completed them

Let us know if anything breaks!
